import requests
import base64

class UpdateRepository:
    def __init__(self, username):
        self.username = username
        self.api_base_url = 'https://api.github.com'
        self.access_token='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'
        self.headers = {'Authorization':"Bearer " + self.access_token,
                        'X-GitHub-Api-Version': '2022-11-28'}

    def create_repo(self, name_repo):
        data = {
            "name": name_repo,
            "description": "Repository with companies programming languages. This file was generated by Python script which gets information from amazon repositories using request library, GET method and saved in this repository, using POST method",
            "private": False
        }
        response = requests.post(f"{self.api_base_url}/user/repos", 
                                 json=data, headers=self.headers)

        print(f'status_code creating repository: {response.status_code}')

    def add_file(self, name_repo, name_file, path_file):

        # Enconding the file
        with open(path_file, "rb") as file:
            file_content = file.read()
        encoded_content = base64.b64encode(file_content)

        # Uploading
        url = f"{self.api_base_url}/repos/{self.username}/{name_repo}/contents/{name_file}"
        data = {
            "message": "Add a new file",
            "content": encoded_content.decode("utf-8")
        }

        response = requests.put(url, json=data, headers=self.headers)
        print(f'status_code file upload: {response.status_code}')

# instantiating an object
new_repo = UpdateRepository('alinept')

# Criando o repositório
name_repo = 'languages_used'
new_repo.create_repo(name_repo)

# Adicionando arquivos salvos no repositório criado
new_repo.add_file(name_repo, 'amzn_languages.csv', 'data/amzn_languages.csv')
new_repo.add_file(name_repo, 'netflix_languages.csv', 'data/netflix_languages.csv')
new_repo.add_file(name_repo, 'spotify_languages.csv', 'data/spotify_languages.csv')